version: "3"

services:
  php:
    build: docker/php-fpm
    volumes:
      - ./docker/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./docker/log/php-fpm:/var/log/php-fpm
      - .:/var/www/html
    links:
      - db:db

  nginx:
    image: nginx:alpine
    ports:
      - ${DOCKER_APP_PORT-8000}:80
    links:
      - php:phpfpm
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - .:/var/www/html
      - ./docker/log/nginx:/var/log/nginx

  db:
    image: mariadb:10.4
    ports:
      - ${DOCKER_DATABASE_PORT-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./docker/mysql/databases:/var/lib/mysql

  composer:
    image: composer:1.7
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: composer install --ignore-platform-reqs --no-scripts

  phpcs:
    build: docker/phpcs
    volumes:
      - .:/var/www/html

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /mnt/swagger.yml
    ports:
      - ${DOCKER_SWAGGER_PORT-8091}:8080
    volumes:
      - .:/mnt
